% Can read from params.yaml to determine exactly which models
models = {'QuadrotorTango', 'QuadrotorUniform', 'QuadrotorVictor', 'QuadrotorWhiskey'} %, 'QuadrotorXray'};

param = {...
    '/formation_offsets'};

radius = 2;
yaw_offset = 3*pi/4;

%% Header
str = sprintf([...
    '# Do not edit this file! It is automatically generated, and any changes\n', ...
    '# you make may be overwritten. See params_generator.m to make changes\n', ...
    '# and regenerate the file.\n\n']);

%% Model names
str = sprintf([str, 'model_names: [']);
for qidx = 1:length(models)
    if qidx < length(models)
        str = sprintf([str, '\n  "', models{qidx}, '",']);
    else
        str = sprintf([str, '\n  "', models{qidx}, '"]\n\n']);
    end
end

%% Formation offsets

angle_offset = 3*pi/4;
for qidx = 1:length(models)
    for pidx = 1:length(param)
        
        angle = angle_offset - qidx / length(models) * 2 * pi;
        
        val = [];
        switch param{pidx}
            case '/formation_offsets'
                str = sprintf([str, '%s: [%2.2f, %2.2f, %2.2f, %2.2f]\n'], ...
                    ['/', models{qidx}, param{pidx}], ...
                    radius * cos(angle), ...
                    radius * sin(angle), ...
                    0, 0);
        end
        
        
    end
end

%% File writing
fid = fopen('params.yaml', 'w');
fprintf(fid, '%s', str);
fclose(fid);
